mallfoundry/taroify

packages/core/src/pagination/pagination.tsx

[Pagination] Fix page can be negative number 

---

packages/core/src/styles/ellipsis.scss
packages/core/src/styles/mixins/_ellipsis.scss

[ellipsis] Merge multi-ellipsis into ellipsis

---

packages/core/src/image/image.tsx

[Image] Fix that onload and onError events does not exist

---

packages/core/src/swiper/swiper.tsx

[Swiper] Fix white screen when offset reset

---

packages/core/src/swipe-cell/swipe-cell.tsx

#494 [SwipeCell需要加入滑动拦截](https://github.com/mallfoundry/taroify/issues/494)

[SwipeCell] Fix catch move 

---

packages/core/src/loading/loading.scss

[Loading] Fix compiled warning

---

packages/core/src/button/README.md
packages/core/src/button/button.shared.ts

[Button] Update the shape prop document

---

packages/core/src/swipe-cell/README.md
packages/core/src/swipe-cell/swipe-cell.tsx

修复 [Bug Report] ScrollView嵌套Swipecell无法正常上下滚动 #528

[SwipeCell] Add the catchMove prop

---

packages/core/src/number-keyboard/number-keyboard-icons.scss

https://github.com/mallfoundry/taroify/issues/527

[NumberKeyboard] Fix Postcss warning of number-keyboard component

---

packages/core/src/form/README.md
packages/core/src/form/form-list.context.ts
packages/core/src/form/form-list.tsx
packages/core/src/form/form.shared.ts
packages/core/src/form/index.ts
packages/core/src/form/use-form-field.ts
packages/core/src/form/use-form-list.ts
packages/core/src/form/use-form-value.ts
packages/core/src/form/use-form.ts
packages/demo/src/pages/form/form/index.tsx

feat: add Form.list

---

packages/core/src/cell/README.md
packages/core/src/cell/cell-base.tsx
packages/core/src/cell/cell.shared.ts
packages/core/src/cell/cell.tsx
packages/core/src/form/README.md
packages/demo/src/pages/basic/cell/index.tsx

Cell(Form.Item,Field) 添加isLink，arrowDirection 属性

feat: Cell adds isLink, arrowDirection property

---

packages/core/src/navbar/navbar.tsx
packages/gulp/serve.js

Navbar 的 placeholder 属性值默认为 false

[Navbar] Placeholder initial value

---

packages/core/src/picker/picker.tsx

**Bug 修复 🐞**
- 修复 DatatimePicker 多了一个空白

[DatatimePicker]: Fix DatatimePicker blank columns

---

packages/core/src/flex/flex.tsx

修复flex无法渲染文本节点(导致timeline无法渲染)

fix(flex): text child render fail

---

packages/core/src/checkbox/checkbox-group.tsx
packages/core/src/radio/radio-group.tsx

Add generics to Checkbox.Group and Radio.Group for better intellisense and typing

feat: add generic to Checkbox.Group and Radio.Group

---

packages/core/src/uploader/uploader.tsx

fix(uploader): param of onChange is any

---

packages/core/src/popup/README.md
packages/core/src/popup/popup.shared.ts
packages/core/src/popup/popup.tsx

types(Popup): add center option to placement

---

packages/cli/package.json
packages/commerce/package.json
packages/core/package.json
packages/core/src/fixed-nav/__tests__/fixed-nav.test.tsx
packages/core/src/fixed-nav/fixed-nav.tsx
packages/core/src/navbar/__tests__/navbar.test.tsx
packages/demo/src/pages/navigation/fixed-nav/index.tsx

1、Update @testing-library/react to 14.0.0
``` Json
"@testing-library/react": "^14.0.0"
```
2、Improve the test cases for FixedNav

[FixedNav]: Improve test cases

---

packages/core/src/button/__tests__/button.test.tsx
packages/core/src/button/button.tsx

- Remove default parameter from useButtonChildren as these values will always pass.
- Test Cases coverage bumped to 100% for button

Bump Button test case coverage to 100%

---

packages/core/src/input/input.tsx

[Input]: 修复readonly属性

---

packages/core/src/back-top/_variables.scss
packages/core/src/badge/_variables.scss
packages/core/src/navbar/_variables.scss
packages/core/src/pagination/_variables.scss
packages/core/src/slider/_variables.scss
packages/core/src/styles/_variables.scss
packages/core/src/swiper/_variables.scss
packages/core/src/tabbar/_variables.scss

组件默认高亮颜色应该从--primary-color取，而不是--blue

fix: component default highlight color should be primary, not blue

---

packages/core/src/flex/flex.shared.ts

Initial Property added for flex align

Flex Initial Added

---

packages/core/src/image/image.tsx
problems/unconfirmed/src/pages/index/index.tsx

Reverts mallfoundry/taroify#772

Revert "fix: 修复image组件因为多嵌套一层View引起的样式问题"

---

packages/core/src/empty/empty.scss

fix:empty ui

---

packages/core/src/form/form-item.tsx
packages/core/src/form/form.rule.ts

添加formItem组件validateFirst属性，用于只返回第一个失败校验

feat(FormItem): 添加validateFirst属性

---

packages/core/src/form/form-feedback.tsx

form组件设置controlAlign right后，feedback没有向右对齐

feat:FormFeedback优化align对其逻辑

---

packages/core/src/navbar/README.md
packages/core/src/safe-area/safe-area.tsx
packages/core/src/tabbar/README.md
packages/core/src/tag/README.md

[#821](https://github.com/mallfoundry/taroify/pull/821)
[#822](https://github.com/mallfoundry/taroify/pull/822)

 [SafeArea]: 修复顶部安全区距离

---

packages/core/src/datetime-picker/README.md
packages/demo/src/pages/form/datetime-picker/index.tsx

1.完善datetime-picker文档，增加年月日时分的描述和demo
2.原文档demo顺序有误，调整demo展示顺序

doc(date-time-picker): 1.完善年月日时分文档 2.调整demo展示顺序

---

packages/gulp/typescript.js

- change import style to `import _foo from "lodash/foo";`
- replace method usage from `_.foo` to `_foo`
- ensure support for tree shaking
https://github.com/mallfoundry/taroify/issues/800

build: change lodash usage in dist bundle

---

packages/gulp/typescript.js

Reverts mallfoundry/taroify#845

Revert "build: change lodash usage in dist bundle"

---

packages/core/src/calendar/README.md

1、fix docs - DayObject property value
2、add formatter example to docs

[Chore] fix calendar docs

---

packages/core/src/form/form.rule.ts

fix https://github.com/mallfoundry/taroify/issues/855

fix: validateFirst should worked

---

packages/core/src/switch/_variables.scss
packages/core/src/switch/switch.scss

style: 💄 switch 美化

---

packages/core/src/utils/dom/portal.ts

fix: 🐛 新增常驻父节点

---

packages/core/src/divider/README.md
packages/core/src/divider/_variables.scss
packages/core/src/divider/divider.scss
packages/core/src/divider/divider.shared.ts
packages/core/src/divider/divider.tsx
packages/demo/src/pages/display/divider/index.tsx

feat(Divider): 🎸 Divider support vertical direction

---

packages/core/src/text-ellipsis/README.md
packages/core/src/text-ellipsis/index.ts
packages/core/src/text-ellipsis/text-ellipsis.tsx
packages/demo/src/pages/display/rolling-text/index.tsx
packages/demo/src/pages/display/text-ellipsis/index.tsx

[TextEllipsis]: TextEllipsis support toggle function

---

packages/core/src/skeleton/README.md
packages/core/src/skeleton/_variables.scss
packages/core/src/skeleton/index.scss
packages/core/src/skeleton/index.ts
packages/core/src/skeleton/skeleton-avatar.scss
packages/core/src/skeleton/skeleton-avatar.tsx
packages/core/src/skeleton/skeleton-image.scss
packages/core/src/skeleton/skeleton-image.tsx
packages/core/src/skeleton/skeleton-paragraph.scss
packages/core/src/skeleton/skeleton-paragraph.tsx
packages/core/src/skeleton/skeleton-title.scss
packages/core/src/skeleton/skeleton-title.tsx
packages/core/src/skeleton/skeleton.scss
packages/core/src/skeleton/skeleton.shared.ts
packages/core/src/skeleton/skeleton.tsx
packages/demo/src/pages/display/skeleton/index.scss
packages/demo/src/pages/display/skeleton/index.tsx

[Skeleton]: 💡 Re implement the skeleton

---

packages/core/src/dropdown-menu/dropdown-menu.tsx
packages/core/src/floating-bubble/floating-bubble.tsx
packages/core/src/floating-panel/README.md
packages/core/src/floating-panel/__tests__/floating-panel.test.tsx
packages/core/src/floating-panel/floating-panel.tsx
packages/core/src/hooks/use-canvas.ts
packages/core/src/safe-area/__tests__/safe-area__outbrowser.test.tsx
packages/core/src/utils/format/unit.ts
packages/core/src/utils/version.ts
packages/core/src/watermark/watermark.tsx
packages/demo/src/pages/action/floating-panel/index.tsx

[wx]: 💡 replace getSystemInfoSync

---

packages/core/src/floating-panel/README.md
packages/core/src/floating-panel/floating-panel.tsx
packages/demo/src/pages/action/floating-panel/index.tsx

- 在 FloatingPanel 组件中添加 setHeight 方法，可通过 ref 调用
- 更新 README.md，添加手动设置高度的示例和 API 文档
- 在示例页面中添加手动设置高度的演示
✅ Closes: #882

feat: 🎸 floating-panel: 添加手动设置高度功能

---

packages/core/src/dialog/README.md
packages/core/src/dialog/_variables.scss
packages/core/src/dialog/dialog.scss
packages/core/src/dialog/dialog.shared.ts

dialog 新增 css 变量 --dialog-header-font-weight 和 --dialog-has-title-message-font-weight

feat(Dialog): dialog支持设置 message 的 font-weight

---

packages/core/src/field/README.md
packages/demo/src/pages/form/field/index.tsx

fix doc typo, https://taroify.github.io/taroify.com/components/field/ 身份证的placeholder应该为请输入身份证号

doc(Field): placeholder msg

---

packages/core/src/calendar/calendar-header.tsx
packages/core/src/calendar/calendar.tsx
packages/demo/src/pages/form/calendar/index.tsx

支持配置是否显示主标题
