packages/core/src/notice-bar/notice-bar.tsx

NoticeBar 动态渲染（例如在 Tabs.TabPane 中），useReady 不会触发，使用只执行一次的 useEffect 解决。

fix(NoticeBar): start scrolling when render

---

packages/core/src/image/image.scss

`display: none` 改变会导致对同一张图片再次发出请求，因此设置宽高为 0 达到相同效果，`position: fixed` 使图片在加载时脱离文档流，防止意外的 layout shifting

fix(Image): display none cause request twice

---

packages/demo/config/dev.js
packages/demo/config/index.js
packages/demo/package.json

Total bundle size in development mode 3.5MB -> 1.78MB (almost **50% off**)
> based on a few commits after 0.0.17-alpha.1, commit: 9ef31ef280b247c232ac7990f22c690b59b2bb8d 
There is **_NO NEED_** to turn on terser plugin for the demo package taking belows into account:
* enable remote debugging in various mini-program devtools with full source map support under bundle size limit of 2MB
* we configure the terser plugin to minimize the SELECTED BUNDLES ONLY
首页见

bundle size reduction for demo package in development mode

---

packages/core/src/image/image.scss

`position: fixed` 导致 Image 在滚动列表中不加载

fix(Image): lazyLoad broken in scrollView

---

packages/core/src/utils/dom/element.ts

使用CustomWarpper组件后，会造成DropdownMenu无法使用，应该是跨自定义组件无法直接使用#id选择器。
https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.select.html
我简单尝试着修复了一下， 但没有详细验证影响的范围， 所以仅供参考吧

createNodesRef 微信小程序跨自定义组件

---

packages/core/src/calendar/calendar.tsx

修复构建项目时ts类型报错问题
Node：v16.13.1
[10:41:04] Starting 'compile typescript files to bundles/core from packages/core'...
packages/core/src/calendar/calendar.tsx(425,20): error TS2349: This expression is not callable.
Type 'typeof import("/Users/liankaa/Documents/www/new_liankaa/taroify/node_modules/classnames/index")' has no call signatures.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[10:41:09] 'compile typescript files to bundles/core from packages/core' errored after 4.83 s
[10:41:09] Error: TypeScript: Compilation failed
at Output.mightFinish (/Users/liankaa/Documents/www/new_liankaa/taroify/node_modules/gulp-typescript/release/output.js:131:43)
at /Users/liankaa/Documents/www/new_liankaa/taroify/node_modules/gulp-typescript/release/output.js:44:22
at runMicrotasks …

[Calendar] Fix "This expression is not callable"

---

packages/core/src/badge/badge.tsx

修复badge 在content={0} dot={false}下会直接渲染一个0而不是渲染后面的View的bug

[Badge] Fix rendering to 0 when content is 0

---

packages/core/src/safe-area/safe-area.scss

safeArea  添加兼容性 css 函数
_**The env() function shipped in iOS 11 with the name constant(). Beginning with Safari Technology Preview 41 and the iOS 11.2 beta, constant() has been removed and replaced with env(). You can use the CSS fallback mechanism to support both versions, if necessary, but should prefer env() going forward.**_

[SafeArea] Add compatibility constant function

---

packages/core/src/utils/dom/element.ts

当页面的根元素为 `Block` 时，`createSelectorQuery().select("#".concat(ancestor.uid, ">>>#").concat(element.uid))` 查询不到信息。导致控制台报错
```tsx
import { Block } from '@tarojs/components'
export default function () {
return (
<Block>
<Calendar type="single" />
</Block>
)
}
```

[ancestorCustomWrapper] Fix getRect nested in a Block element does not query elements

---

packages/core/src/utils/dom/event.ts

支付宝小程序不返回 touches，如果没有clientX 和 clientY，则从 detail 中获取

fix: alipay Click Event detail

---

packages/core/src/utils/dom/event.ts

由于使用微信小程序点击右侧导航，定位报错，发现是上一个人为了支持支付宝，把微信改坏了，所以修改一下

fix：WeChat mini program Click Event detail

---

packages/core/src/tabs/tab-pane-base.tsx

fix: remove title prop in TabPane content dom

---

packages/core/src/watermark/watermark.tsx

Importing .scss file inside the component is causing an error while using it inside a taro project.

Update watermark.tsx (index.scss import removed)

---

packages/core/src/input/native-input.scss

修复 Input 组件的 font-size 无法被正常继承。

fix: font-size of input cannot be inherited

---

packages/core/src/fixed-nav/fixed-nav.tsx

Console.log statement removed from fixed-nav component.

Removed console.log statement

---

packages/core/src/datetime-picker/use-datetime-picker.ts

DatetimePicker可选择月和日的情况下，由于代码中先设置月份，会导致所有最后一天小于minDate的日的月份被设置为下一个月。

fix(DatetimePicker): get wrong month when the day is at the boundary

---

packages/gulp/typescript.js

修复taro预编译@taroify/core, @taroify/icons失败
export { default as Button } from "./button"
在esbuild0.18.0 (taro 3.6.20) 版本以后node_modules里./button会匹配上./button/index.css和./button/index.js，之前版本只会匹配./button/index.js，导致预编译时加载是./button/index.css而不是js文件，因而预编译失败。需要添加上.js扩展名
之前写的正则和判断条件有问题 😰。。。.js扩展名实际上未添加上，预编译仍然有问题。

build: fix taro prebuild fail

---

packages/core/src/safe-area/__tests__/__snapshots__/safe-area__inbrowser.test.tsx.snap
packages/core/src/safe-area/__tests__/__snapshots__/safe-area__outbrowser.test.tsx.snap
packages/core/src/safe-area/__tests__/safe-area__inbrowser.test.tsx
packages/core/src/safe-area/__tests__/safe-area__outbrowser.test.tsx
packages/core/src/safe-area/safe-area.tsx

fix: SafeArea小程序环境下，不传入position时的异常判断
Test: SafeArea新增单测

[SafeArea] fix and add Test

---

packages/core/src/pull-refresh/pull-refresh.tsx
packages/gulp/__tests__/treeshaking-lodash.test.js
packages/gulp/treeshaking-lodash.js
packages/gulp/typescript.js

将
```js
import { debounce, throttle, get as mGet } from "lodash";
import * as _ from "lodash";
import util from "lodash";
console.log(mGet(), util.set(), _.map())
```
转换为
```js
import debounce from "lodash/debounce";
import throttle from "lodash/throttle";
import mGet from "lodash/get";
import _map from "lodash/map";
import utilset from "lodash/set";
console.log(mGet(), utilset(), _map())
```
已知以下为处理(代码里不存在)
1.lodash/fp
2.import "lodash"
3.import { get as _get } from "lodash"; import _ as from "lodash"; console.log(_get(), _.get())

build: tree shaking lodash

---

packages/core/src/navbar/README.md

文档里bordered默认值写的true，实际默认值为false。

[Navbar]docs: fix the default value of 'bordered'

---

packages/core/src/popup/popup.tsx
packages/demo/src/pages/basic/popup/index.tsx

- 在 useEffect 中添加 initializedRef 以判断组件是否已初始化
- 优化 Popup 关闭逻辑，仅在组件初始化后执行关闭回调
- 移除 demo 中未使用的 ArrowRight 图标导入"
✅ Closes: #941 #942

fix(popup): 🐛Popup 组件初次挂载时会执行 onClose 事件

---

packages/core/src/transition/transition.tsx

添加 nodeRef 属性，并使用 cloneElement 为子元素添加 ref 属性以解决 React18 findDOMNode API报错问题
✅ Closes: #947
参考: https://github.com/reactjs/react-transition-group/issues/918#issuecomment-2653832792
`react-transition-group`这个库看起来已经不维护很久了

fix: 🐛 修复 Transition 组件的 findDOMNode API报错问题

---

packages/core/src/dialog/dialog.tsx

在 dialog.tsx 的 renderHeader 中添加了对 title 的空值校验

fix(Dialog): 未传入 title 时仍然渲染 header 的问题

---

packages/core/src/uploader/README.md
packages/core/src/uploader/uploader.tsx
packages/demo/src/pages/form/uploader/index.tsx

✅ Closes: #965
官网自定义渲染例子存在bug
children被透传至UploaderUpload使用，当children不止为上传按钮，存在UploaderImage时会重复渲染。
修复这个 bug 需要不透传 children 与“自定义上传样式”示例实现冲突
增加 itemRender 用来实现自定义上传项，兼容老代码
0.4.1版本 uploader 调整导致

fix: 🐛 增加itemRender用来修复使用react chidlren属性时图片重复渲染
